#!/usr/bin/env python3
# 04.04.2017
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

param = 4000000

fib = 1
lastfib = 0

erg = 0
while fib < param:
	if (fib%2)==0: 
		erg += fib
	newfib = lastfib + fib
	lastfib = fib
	fib = newfib

print(erg)
